project_id = "zinc-fusion-v16"

[api]
enabled = false
schemas = ["public", "mkt", "econ", "alt", "supply", "training", "forecasts", "analytics", "ops", "vegas"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 17

[studio]
enabled = false

[inbucket]
enabled = false
